module.exports = {
  apps: [
    {
      name: "n8n-backend",
      cwd: "./apps/backend",
      script: "yarn",
      args: "dev",
      env: {
        NODE_ENV: "development",
        PORT: 4019,
        WS_PORT: 4020,
      },
      watch: ["src"],
      ignore_watch: ["node_modules", "dist"],
      instances: 1,
      autorestart: true,
      max_memory_restart: "1G",
      log_file: "./logs/backend.log",
      out_file: "./logs/backend-out.log",
      error_file: "./logs/backend-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "n8n-frontend",
      cwd: "./apps/frontend",
      script: "yarn",
      args: "dev",
      env: {
        NODE_ENV: "development",
        VITE_API_URL: "http://localhost:4019/graphql",
        VITE_WS_URL: "ws://localhost:4020/graphql",
      },
      watch: ["src"],
      ignore_watch: ["node_modules", "dist"],
      instances: 1,
      autorestart: true,
      max_memory_restart: "1G",
      log_file: "./logs/frontend.log",
      out_file: "./logs/frontend-out.log",
      error_file: "./logs/frontend-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
