services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-n8n-1755903269929-p1ic5w2m0
    restart: unless-stopped

    # Port mapping
    ports:
      - "5601:5678"

    # Environment variables
    environment:
      # Basic authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123

      # Server configuration
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=false

      # Security and performance
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - N8N_ENCRYPTION_KEY=5c21bbdce154d21890b93d60dacfc84ac775bf496aaf91ca4684e79bfb33ef3c

      # Webhook configuration
      - WEBHOOK_URL=http://localhost:5601
      - GENERIC_TIMEZONE=UTC

      # Database (using SQLite for simplicity)
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite

      # Execution settings
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=regular
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200

      # Queue settings
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0

    # Volumes for persistent data
    volumes:
      - n8n_data_n8n-1755903269929-p1ic5w2m0:/home/node/.n8n
      - n8n_workflows_n8n-1755903269929-p1ic5w2m0:/home/node/.n8n/workflows
      - n8n_credentials_n8n-1755903269929-p1ic5w2m0:/home/node/.n8n/credentials

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Labels for Traefik routing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-n8n-1755903269929-p1ic5w2m0.rule=Host(`ContrutoraPro.n8n.local`)"
      - "traefik.http.routers.n8n-n8n-1755903269929-p1ic5w2m0.entrypoints=web"
      - "traefik.http.services.n8n-n8n-1755903269929-p1ic5w2m0.loadbalancer.server.port=5678"
      - "traefik.http.middlewares.n8n-n8n-1755903269929-p1ic5w2m0-auth.basicauth.users=admin:YWRtaW46YWRtaW4xMjM="
      - "traefik.http.routers.n8n-n8n-1755903269929-p1ic5w2m0.middlewares=n8n-n8n-1755903269929-p1ic5w2m0-auth"

      # Custom labels for management
      - "n8n.instance.id=n8n-1755903269929-p1ic5w2m0"
      - "n8n.client.name=ContrutoraPro"
      - "n8n.port=5601"
      - "n8n.subdomain=ContrutoraPro"
      - "n8n.created=2025-08-22T22:54:29.953Z"

    # Network configuration
    networks:
      - n8n_network_n8n-1755903269929-p1ic5w2m0

    # Dependencies
    depends_on:
      - redis

  # Redis for queue management
  redis:
    image: redis:7-alpine
    container_name: n8n-redis-n8n-1755903269929-p1ic5w2m0
    restart: unless-stopped

    # Redis configuration
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

    # Volumes for Redis persistence
    volumes:
      - n8n_redis_n8n-1755903269929-p1ic5w2m0:/data

    # Resource limits for Redis
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

    # Health check for Redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

    # Labels
    labels:
      - "n8n.instance.id=n8n-1755903269929-p1ic5w2m0"
      - "n8n.component=redis"

    # Network
    networks:
      - n8n_network_n8n-1755903269929-p1ic5w2m0

# Volumes for persistent data
volumes:
  n8n_data_n8n-1755903269929-p1ic5w2m0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  n8n_workflows_n8n-1755903269929-p1ic5w2m0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./workflows
  n8n_credentials_n8n-1755903269929-p1ic5w2m0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./credentials
  n8n_redis_n8n-1755903269929-p1ic5w2m0:
    driver: local

# Networks
networks:
  n8n_network_n8n-1755903269929-p1ic5w2m0:
    driver: bridge
    ipam:
      config:
        - subnet: 172.211.0.0/16
